//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class application
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public application()
        {
            this.interviews = new HashSet<interview>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid user_id { get; set; }
        public System.Guid opportunity_id { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> applied_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual opportunity opportunity { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<interview> interviews { get; set; }
    }
}
