//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class audit_logs
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public string action { get; set; }
        public string table_name { get; set; }
        public Nullable<System.Guid> record_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        public virtual user user { get; set; }
    }
}
