//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bursary
    {
        public System.Guid id { get; set; }
        public string title { get; set; }
        public string sponsor { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string requirements { get; set; }
        public Nullable<System.DateTime> closing_date { get; set; }
    }
}
