//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public company()
        {
            this.company_users = new HashSet<company_users>();
            this.opportunities = new HashSet<opportunity>();
        }
    
        public System.Guid id { get; set; }
        public string company_name { get; set; }
        public string registration_number { get; set; }
        public string industry { get; set; }
        public Nullable<System.Guid> district_id { get; set; }
        public Nullable<bool> verified { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public string website { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string logo_url { get; set; }
        public string description { get; set; }
        public string physical_address { get; set; }
        public string ContactPerson { get; set; }
    
        public virtual district district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company_users> company_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opportunity> opportunities { get; set; }
    }
}
