//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_users
    {
        public System.Guid company_id { get; set; }
        public System.Guid user_id { get; set; }
        public string role { get; set; }
    
        public virtual company company { get; set; }
        public virtual user user { get; set; }
    }
}
