//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class document
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> user_id { get; set; }
        public string document_type { get; set; }
        public string file_url { get; set; }
        public Nullable<bool> is_verified { get; set; }
        public Nullable<System.DateTime> uploaded_at { get; set; }
    
        public virtual user user { get; set; }
    }
}
