//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class education
    {
        public System.Guid id { get; set; }
        public System.Guid user_id { get; set; }
        public string institution_name { get; set; }
        public string qualification { get; set; }
        public string field_of_study { get; set; }
        public string level { get; set; }
        public Nullable<System.DateTime> start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public Nullable<bool> completed { get; set; }
    
        public virtual user user { get; set; }
        public virtual youth_profiles youth_profiles { get; set; }
    }
}
