//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class interview
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> application_id { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public string interview_mode { get; set; }
        public string notes { get; set; }
        public string status { get; set; }
    
        public virtual application application { get; set; }
    }
}
