//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class opportunity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public opportunity()
        {
            this.applications = new HashSet<application>();
            this.opportunity_documents = new HashSet<opportunity_documents>();
            this.skills = new HashSet<skill>();
        }
    
        public System.Guid id { get; set; }
        public System.Guid company_id { get; set; }
        public Nullable<System.Guid> category_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string location { get; set; }
        public Nullable<System.Guid> district_id { get; set; }
        public string requirements { get; set; }
        public Nullable<decimal> stipend { get; set; }
        public Nullable<System.DateTime> closing_date { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<application> applications { get; set; }
        public virtual company company { get; set; }
        public virtual district district { get; set; }
        public virtual opportunity_categories opportunity_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opportunity_documents> opportunity_documents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<skill> skills { get; set; }
    }
}
