//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class password_resets
    {
        public System.Guid id { get; set; }
        public System.Guid user_id { get; set; }
        public string reset_token { get; set; }
        public System.DateTime expires_at { get; set; }
        public Nullable<bool> used { get; set; }
    
        public virtual user user { get; set; }
    }
}
