//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RoyalPortalDbEntities : DbContext
    {
        public RoyalPortalDbEntities()
            : base("name=RoyalPortalDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<analytics_events> analytics_events { get; set; }
        public virtual DbSet<application> applications { get; set; }
        public virtual DbSet<audit_logs> audit_logs { get; set; }
        public virtual DbSet<bursary> bursaries { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<company_users> company_users { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<document> documents { get; set; }
        public virtual DbSet<education> educations { get; set; }
        public virtual DbSet<@event> events { get; set; }
        public virtual DbSet<generated_cvs> generated_cvs { get; set; }
        public virtual DbSet<interest> interests { get; set; }
        public virtual DbSet<interview> interviews { get; set; }
        public virtual DbSet<opportunity> opportunities { get; set; }
        public virtual DbSet<opportunity_categories> opportunity_categories { get; set; }
        public virtual DbSet<opportunity_documents> opportunity_documents { get; set; }
        public virtual DbSet<partner> partners { get; set; }
        public virtual DbSet<password_resets> password_resets { get; set; }
        public virtual DbSet<skill> skills { get; set; }
        public virtual DbSet<user_courses> user_courses { get; set; }
        public virtual DbSet<user_sessions> user_sessions { get; set; }
        public virtual DbSet<user_skills> user_skills { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<verification> verifications { get; set; }
        public virtual DbSet<work_experience> work_experience { get; set; }
        public virtual DbSet<youth_profiles> youth_profiles { get; set; }
    }
}
