//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recruitment_Portal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_skills
    {
        public System.Guid user_id { get; set; }
        public System.Guid skill_id { get; set; }
        public string proficiency_level { get; set; }
    
        public virtual skill skill { get; set; }
        public virtual user user { get; set; }
    }
}
